- name: UPFOS
  link: https://upfos.com
- name: UPFOS ERP
  link: https://go.upfos.com
- name: UPFOS Chat
  link: https://go.upfos.com/main-4-2-0.html#/chat
- name: UPFOS Mobile
  link: https://upfos.xyz/mobile